import Head from 'next/head';
import NavBar from '@/components/NavBar';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';

export default function Home() {
  return (
    <>
      <NavBar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full min-h-screen text-dark">
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={profilePic} alt="Mykola" className="w-full h-auto" />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
